# Generated by Django 4.1.3 on 2022-12-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenctication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="phone_number",),
    ]
