# Generated by Django 4.1.3 on 2022-12-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="date the question was posted"
            ),
        ),
    ]
