# Generated by Django 4.1.3 on 2022-12-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trivia_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="triviauser", old_name="gu_id", new_name="tu_id",
        ),
    ]
